import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../stylesheets/main.scss';

import Header from '../components/header'

const inter = Inter({ 
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Brian Lai',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				{children}
			</body>
		</html>
	);
}
